name: electron-app
version: '1.0.0'
summary: App summary
description: |
  App description
base: core18
grade: devel
confinement: devmode

parts:
  electron-deps:
    plugin: nil
    after:
    - desktop-gtk3
    stage-packages:
    - libnotify4
    - libnss3
    - libpcre3
    - libuuid1
    - libxss1
    - libxtst6
